### ISSUE TITLE
Register static accessors in model

### ISSUE THREAD

**Issue by RemiEven** [aksyonov/mongoose-class-wrapper#6]
Hi,

it seems that static getters and setters are not registered in the model, as shown by the following test cases (both failing):

``` js
it('should register static getters in model', function () {
  class UserModel {
    static get password() { return 'encrypted' }
  }
  loadClass(this.schema, UserModel);
  let User = mongoose.model('User', this.schema);
  expect(User.password).to.eql('encrypted');
});

it('should register static setters in model', function () {
  class UserModel {
    static set password(value) { this._pass = value }
  }
  loadClass(this.schema, UserModel);
  let User = mongoose.model('User', this.schema);
  User.password = 'pass';
  expect(User._pass).to.eql('pass');
});
```

I tried to correct it myself, but due to the lack of method both virtual and static in mongoose I didn't succeed. Any idea on how to proceed in this case ? Thanks :)

**Comment by aksyonov** [comment]
I don't think that it's possible. As you said there is no method in mongoose to register static virtual methods. Also when plugin is working, model is not yet created, so we can't use `Object.defineProperty`.

**Comment by RemiEven** [comment]
Ok, I understand. This is not a big issue, as we can still use static methods, so it wasn't blocking me anyway. Thanks for your reply, I let you close this if you want.
