### ISSUE TITLE
Import error on TypeScript 1.8

### ISSUE THREAD

**Issue by netpedro-com** [aksyonov/mongoose-class-wrapper#8]
To properly import this library using `TypeScript 1.8`, instead `import loadClass from 'mongoose-class-wrapper';` I must use `import loadClass = require('mongoose-class-wrapper');`. This issue is described in rich detail in:
- [export = and import = require()](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require)
- [ES6 Modules default exports interop with CommonJS](https://github.com/Microsoft/TypeScript/issues/2719)

Based on this, I think it's suited add an advice in `README.md` alerting the typescript user or maybe change the source code to tackle this issue.

**Comment by aksyonov** [comment]
@pedrovagner, thanks for creating this issue, I added some notes about this into example in `README.md`. Also if you have any ideas how to make this library more typescript-friendly please let me know or create pull request.

**Comment by netpedro-com** [comment]
Nice @aksyonov, I just see the changes in `README.md`, but `mongoose` import is different from mine. Although it's not wrong, mine is more `ES6`. To make things clearer, this is my setup:

``` typescript
// foo.ts
import * as mongoose from 'mongoose';
import loadClass = require('mongoose-class-wrapper');

// typings.d.ts
declare module 'mongoose-class-wrapper' {
  function loadClass(schema: any, target: any): void;
  export = loadClass;
}
```

`mongoose` typings was installed using `typings install mongoose --source dt --save --global`. TypeScript compiles to JavaScript obeying typings definition files. I didn't found any way to declare `mongoose-class-wrapper` to obey `import loadClass from 'mongoose-class-wrapper'`. In my point of view, TypeScript is awkward; I hope `TypeScript 2.0` improve this. For now, `import loadClass = require('mongoose-class-wrapper')` is enough.

By the way, thanks for make this library @aksyonov. If I see issues, I'll try resolve it.

**Comment by aksyonov** [comment]
Thanks, I updated `README.md`. Also I added `.d.ts` file, but didn't test that it works correctly.

**Comment by netpedro-com** [comment]
I just test it, works nice.
