### ISSUE TITLE
Missing Static Variables Register

### ISSUE THREAD

**Issue by netpedro-com** [aksyonov/mongoose-class-wrapper#9]
Why not register static variables? I just see the source code and only static methods get registered. Is that a design constraint?

**Comment by aksyonov** [comment]
Hello, there was similar issue #6. The reason behind this issue is that `mongoose` provides only methods to register instance methods, getters, setters and static methods. Unfortunately, there is no methods in `mongoose` for registering static variables or getters/setters.

**Comment by netpedro-com** [comment]
Before open this issue, I had seen #6. I thought that concepts discussed there (virtual static getters/setters) doesn't apply to static variables. And I still thinking `schema.static` works with static variables (works in node REPL). It's only a matter of filter this properties/descriptors before register. Note: don't take seriously what I say, I just have a month into Node development. Feel free to close this issue, thanks.
